name: Last commit


on: [workflow_dispatch]
       
jobs:
  push_to_registries:
    name: Remove last commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
      packages: write 
    steps:             
                    
      - name: Check out the repo
        uses: actions/checkout@v2      
                
          

      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit --allow-empty -n -m "Initial commit"
          git reset --hard HEAD^

          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master     
