name: Last commit


on: push

   
jobs:
  push_to_registries:
    name: Remove last commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
      packages: write 
    steps:             
                    
      - uses: actions/checkout@v3
      - run: |          
          git show-ref --tags >> tag.txt
          cat tag.txt

          
