name: Last commit


on: [workflow_dispatch]

   
jobs:
  push_to_registries:
    name: Remove last commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
      packages: write 
    steps:             
                    
      - uses: actions/checkout@v3
      - run: |
          git pull 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git log --oneline --graph

          
